// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT1CxCNqricDZg_4HnCDe4-WNfb2u__iY',
    appId: '1:403608153036:web:4bfa37f12529f7f8608b69',
    messagingSenderId: '403608153036',
    projectId: 'portfolio-6ae20',
    authDomain: 'portfolio-6ae20.firebaseapp.com',
    storageBucket: 'portfolio-6ae20.firebasestorage.app',
    measurementId: 'G-GQFW6FPVZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kyy016_xm8K1_8r-KaWiYjKaHjLMrgk',
    appId: '1:403608153036:android:3de84d74387b6be6608b69',
    messagingSenderId: '403608153036',
    projectId: 'portfolio-6ae20',
    storageBucket: 'portfolio-6ae20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVtPR8fHw7NEYj0HT31EZZ0HLm4Y3tkZU',
    appId: '1:403608153036:ios:c08d85bd7b80e23a608b69',
    messagingSenderId: '403608153036',
    projectId: 'portfolio-6ae20',
    storageBucket: 'portfolio-6ae20.firebasestorage.app',
    iosBundleId: 'com.manishsoni.portfolio',
  );
}
